# Generated by Django 5.2.6 on 2025-09-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='auth_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
