# Generated by Django 5.2.6 on 2025-10-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_student_auth_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('PENDING', 'Pending')], default='PRESENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
