# Generated by Django 5.2.6 on 2025-10-18 15:11

import django.db.models.deletion
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_attendancerecord_status_alter_classroom_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_type', models.CharField(choices=[('MEDICAL', 'Medical'), ('EVENT', 'Event'), ('HACKATHON', 'Hackathon'), ('OTHER', 'Other')], max_length=20)),
                ('reason_description', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=user.models.absence_document_upload_path)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_proposals', to='user.student')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
