# Generated by Django 5.2.6 on 2025-10-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_absenceproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absenceproposal',
            name='reason_type',
            field=models.CharField(choices=[('MEDICAL', 'Medical'), ('EVENT', 'Event'), ('ACADEMIC', 'academic'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
